In [23]:
import numpy as np 
import pandas as pd

In [24]:
df = pd.read_csv(r"C:\Users\rampa\DS Python Class\Baking Loan\Data\Cleande data\banking_loan_cleand_data.csv")

### Age Group

Age groups are created to categorize customers into meaningful age ranges.
This makes it easier to analyze customer behavior, loan patterns, approval rates, and payment delays across different age groups.

In [25]:
def age_group(age):
    if age <= 25:
        return "Young"
    elif age <= 40:
        return "Adult"
    elif age <= 55:
        return "Senior"
    else:
        return "Older"

df["Age_Group"] = df["age"].apply(age_group)
df["Age_Group"].unique()

array(['Adult', 'Older', 'Senior', 'Young'], dtype=object)

### Application Year

The `Application_Year` column is created from the `Application_Date` column to analyze loan applications on a year-wise basis. This helps identify trends and changes in loan applications over different years.

In [26]:
#Convert Application Date

#When data is imported from a CSV file, the Application_Date column may not be recognized as a date datatype.
#Therefore, it is converted to the datetime datatype before performing date-based analysis such as extracting the application year.

df["application_date"] = pd.to_datetime(df["application_date"])
df["application_Year"] = df["application_date"].dt.year

# Check the result
df[["application_date", "application_Year"]].head()

  application_date  application_Year
0       2024-04-12              2024
1       2025-03-11              2025
2       2026-05-10              2026
3       2024-09-27              2024
4       2024-04-16              2024

### Application Month

The `Application_Month` column is created from the `Application_Date` column to analyze loan applications on a month-wise basis. 
This helps identify monthly trends and patterns in loan applications.

In [27]:
df["Application_Month"] = df["application_date"].dt.month_name()
df[["application_date", "Application_Month"]].head()

  application_date Application_Month
0       2024-04-12             April
1       2025-03-11             March
2       2026-05-10               May
3       2024-09-27         September
4       2024-04-16             April

### Income Segment

The `Income_Segment` column is created by grouping customers based on their annual income. This makes it easier to analyze loan applications, approval status, loan amounts, and payment behavior across different income groups.

In [28]:
def income_segment(income):
    if income <= 300000:
        return "Low"
    elif income <= 600000:
        return "Medium"
    else:
        return "High"

df["Income_Segment"] = df["annual_income"].apply(income_segment)

### Credit Score Segment

The `Credit_Score_Segment` column is created to categorize customers based on their credit scores. This helps analyze loan approval, loan status, and payment behavior across different credit score categories.

In [29]:
def credit_score_band(score):
    if score < 580:
        return "Poor"
    elif score < 670:
        return "Fair"
    else:
        return "Good"

df["Credit_Score_Band"] = df["credit_score"].apply(credit_score_band)

### Payment Delay Category

The `Delay_Category` column is created by grouping customers based on the number of payment delay days. This helps analyze customer payment behavior and identify customers with different levels of payment delays.

In [30]:
def delay_category(days):
    if days == 0:
        return "No Delay"
    elif days <= 30:
        return "Low Delay"
    elif days <= 60:
        return "Moderate Delay"
    else:
        return "High Delay"

df["Delay_Category"] = df["payment_delay_days"].apply(delay_category)

In [31]:
df.columns.tolist()

['customer_id',
 'application_date',
 'age',
 'gender',
 'employment_type',
 'annual_income',
 'city',
 'credit_score',
 'loan_type',
 'loan_tenure_years',
 'loan_amount',
 'approval_status',
 'loan_status',
 'payment_delay_days',
 'Age_Group',
 'application_Year',
 'Application_Month',
 'Income_Segment',
 'Credit_Score_Band',
 'Delay_Category']

In [32]:
df[
    [
        "Age_Group",
        "application_Year",
        "Application_Month",
        "Income_Segment",
        "Credit_Score_Band",
        "Delay_Category"
    ]
].head()

,Age_Group,application_Year,Application_Month,Income_Segment,Credit_Score_Band,Delay_Category
0,Adult,2024,April,Medium,Good,Low Delay
1,Older,2025,March,High,Good,High Delay
2,Senior,2026,May,High,Fair,No Delay
3,Adult,2024,September,High,Good,No Delay
4,Young,2024,April,High,Good,Low Delay

In [33]:
df.to_csv(r"C:\Users\rampa\DS Python Class\Baking Loan\Data\Cleande data\banking_loan_cleand_data.csv",index=False)